Print warnings and errors in initramfs generation consistently
All warning (non-fatal condition) and error (fatal condition)
messages should be printed to stderr, and should start with a
prefix of "W:" or "E:" respectively.

Also remove the word "ignoring" from some warning messages.  It
follows from the fact that they are warnings that the problem is
being ignored.

Signed-off-by: Ben Hutchings <ben@decadent.org.uk>

diff --git a/hook-functions b/hook-functions
--- a/hook-functions
+++ b/hook-functions
@@ -789,7 +789,7 @@ call_scripts()
 		"${initdir}/${cs_x}" && ec=$? || ec=$?
 		# allow hooks to abort build:
 		if [ "$ec" -ne 0 ]; then
-			echo "E: ${initdir}/${cs_x} failed with return $ec."
+			echo "E: ${initdir}/${cs_x} failed with return $ec." >&2
 			# only errexit on mkinitramfs
 			[ -n "${version}" ] && exit $ec
 		fi
diff --git a/hooks/fsck b/hooks/fsck
--- a/hooks/fsck
+++ b/hooks/fsck
@@ -91,13 +91,13 @@ copy_exec /sbin/logsave
 
 for type in $fsck_types; do
 	if [ "$type" = "unknown" ] ; then
-		echo "Warning: couldn't identify filesystem type for fsck hook, ignoring."
+		echo "W: couldn't identify filesystem type for fsck hook" >&2
 		continue
 	fi
 
 	if prog="$(command -v "fsck.${type}")"; then
 		copy_exec "$prog"
 	else
-		echo "Warning: /sbin/fsck.${type} doesn't exist, can't install to initramfs, ignoring."
+		echo "W: /sbin/fsck.${type} doesn't exist, can't install to initramfs" >&2
 	fi
 done
diff --git a/mkinitramfs b/mkinitramfs
--- a/mkinitramfs
+++ b/mkinitramfs
@@ -74,7 +74,7 @@ done
 # 	 these conf dirs are for boot scripts and land on initramfs
 for i in ${EXTRA_CONF}; do
 	if [ -d  "${CONFDIR}/conf.d/${i}" ]; then
-		echo "Warning: ${CONFDIR}/conf.d/${i} is a directory instead of file, ignoring."
+		echo "W: ${CONFDIR}/conf.d/${i} is a directory instead of file" >&2
 	elif [ -e  "${CONFDIR}/conf.d/${i}" ]; then
 		. "${CONFDIR}/conf.d/${i}"
 	elif [ -e  "/usr/share/initramfs-tools/conf.d/${i}" ]; then
@@ -85,7 +85,7 @@ done
 # source package confs
 for i in /usr/share/initramfs-tools/conf-hooks.d/*; do
 	if [ -d "${i}" ]; then
-		echo "Warning: ${i} is a directory instead of file, ignoring."
+		echo "W: ${i} is a directory instead of file." >&2
 	elif [ -e "${i}" ]; then
 		. "${i}"
 	fi
@@ -159,8 +159,8 @@ fi
 MODULESDIR="/lib/modules/${version}"
 
 if [ ! -e "${MODULESDIR}" ]; then
-	echo "WARNING: missing ${MODULESDIR}"
-	echo "Ensure all necessary drivers are built into the linux image!"
+	echo "W: missing ${MODULESDIR}" >&2
+	echo "W: Ensure all necessary drivers are built into the linux image!" >&2
 fi
 if [ ! -e "${MODULESDIR}/modules.dep" ]; then
 	depmod "${version}"
@@ -250,8 +250,8 @@ list)
 	# nothing to add
 	;;
 *)
-	echo "W: mkinitramfs: unsupported MODULES setting: ${MODULES}."
-	echo "W: mkinitramfs: Falling back to MODULES=most."
+	echo "W: mkinitramfs: unsupported MODULES setting: ${MODULES}." >&2
+	echo "W: mkinitramfs: Falling back to MODULES=most." >&2
 	auto_add_modules
 	;;
 esac
@@ -295,7 +295,7 @@ if [ -n "${ROOT:-}" ]; then
 fi
 
 if ! command -v ldd >/dev/null 2>&1 ; then
-	echo "WARNING: no ldd around - install libc-bin" >&2
+	echo "E: no ldd around - install libc-bin" >&2
 	exit 1
 fi
 
@@ -413,15 +413,15 @@ eval "$(
 	echo "ec3=$?;" >&4
 )"
 if [ "$ec1" -ne 0 ]; then
-	echo "E: mkinitramfs failure find $ec1 cpio $ec2 $compress $ec3"
+	echo "E: mkinitramfs failure find $ec1 cpio $ec2 $compress $ec3" >&2
 	exit "$ec1"
 fi
 if [ "$ec2" -ne 0 ]; then
-	echo "E: mkinitramfs failure cpio $ec2 $compress $ec3"
+	echo "E: mkinitramfs failure cpio $ec2 $compress $ec3" >&2
 	exit "$ec2"
 fi
 if [ "$ec3" -ne 0 ]; then
-	echo "E: mkinitramfs failure $compress $ec3"
+	echo "E: mkinitramfs failure $compress $ec3" >&2
 	exit "$ec3"
 fi
 ) || exit 1
