Add firmware for built-in drivers
There's an old bug report from 2017 (#857054) complaining that firmware for
built-in drivers is not automatically added to initramfs; and back then,
the kernel did not collect information about such dependencies in a place
where initramfs-tools could access it (#857055).

However, since Linux 5.2 (released in mid-2019), the kernel actually
provides this information via modules.builtin.modinfo; you can see at e.g.
<https://packages.debian.org/bullseye/amd64/linux-image-5.7.0-3-amd64/filelist>
that the buster kernel package ships this file. (There aren't actually any
firmware dependencies listed in there though; I guess the upstream Debian
kernel config just has no built-in code with firmware dependencies?)

Wire it up, so that people with custom kernel configs don't have to waste
time figuring out that their devices don't work properly because the
firmware wasn't available at boot.

Closes: #857054

diff --git a/hook-functions b/hook-functions
--- a/hook-functions
+++ b/hook-functions
@@ -50,10 +50,42 @@ add_modules_from_file()
 	done
 }
 
+# Locate a firmware file with the given name and copy it into DESTDIR, unless
+# DESTDIR already contains such a file.
+# Returns an error if no such firmware file can be located and DESTDIR doesn't
+# already contain any matching file. (It is up to the caller to figure out
+# whether a warning should be printed in that case.)
+add_firmware()
+{
+	local firmware fwloc
+
+	firmware="${1}"
+
+	if [ -e "${DESTDIR}/lib/firmware/updates/${version?}/${firmware}" ] \
+	|| [ -e "${DESTDIR}/lib/firmware/updates/${firmware}" ] \
+	|| [ -e "${DESTDIR}/lib/firmware/${version}/${firmware}" ] \
+	|| [ -e "${DESTDIR}/lib/firmware/${firmware}" ]; then
+		return 0
+	fi
+
+	for fwloc in "/lib/firmware/updates/${version}/${firmware}" \
+		"/lib/firmware/updates/${firmware}" \
+		"/lib/firmware/${version}/${firmware}" \
+		"/lib/firmware/${firmware}"; do
+		if [ -e "$fwloc" ]; then
+			copy_file firmware "$fwloc"
+			return 0
+		fi
+	done
+
+	# We can't figure out where to get that firmware from.
+	return 1
+}
+
 # Add dependent modules + eventual firmware
 manual_add_modules()
 {
-	local prefix kmod options firmware fwloc
+	local prefix kmod options firmware
 
 	if [ $# -eq 0 ]; then
 		return
@@ -76,19 +108,9 @@ manual_add_modules()
 
 		# Add required firmware
 		for firmware in $(modinfo -k "${version}" -F firmware "${kmod}"); do
-			if [ -e "${DESTDIR}/lib/firmware/updates/${version}/${firmware}" ] \
-			|| [ -e "${DESTDIR}/lib/firmware/updates/${firmware}" ] \
-			|| [ -e "${DESTDIR}/lib/firmware/${version}/${firmware}" ] \
-			|| [ -e "${DESTDIR}/lib/firmware/${firmware}" ]; then
-				continue
-			fi
-
 			# Only print warning for missing fw of loaded module
 			# or forced loaded module
-			if [ ! -e "/lib/firmware/updates/${version}/${firmware}" ] \
-			&& [ ! -e "/lib/firmware/updates/${firmware}" ] \
-			&& [ ! -e "/lib/firmware/${version}/${firmware}" ] \
-			&& [ ! -e "/lib/firmware/${firmware}" ]; then
+			if ! add_firmware "$firmware"; then
 				# Only warn about missing firmware if
 				# /proc/modules exists
 				if [ ! -e /proc/modules ] ; then
@@ -102,17 +124,32 @@ manual_add_modules()
 				fi
 				continue
 			fi
-
-			for fwloc in "/lib/firmware/updates/${version}/${firmware}" \
-				"/lib/firmware/updates/${firmware}" \
-				"/lib/firmware/${version}/${firmware}" \
-				"/lib/firmware/${firmware}"; do
-				if [ -e "$fwloc" ]; then
-					copy_file firmware "$fwloc"
-					break
-				fi
-			done
 		done
+	done
+}
+
+# manual_add_modules() takes care of adding firmware for things that were built
+# as modules; but drivers can also be built into the kernel itself. To cover
+# that case, we have to look at modules.builtin.modinfo instead.
+# This file is generated by the kernel's build process since commit 898490c010b5
+# ("moduleparam: Save information about built-in modules in separate file"),
+# which was added in Linux 5.2.
+add_builtin_firmware()
+{
+	local builtin_modinfo_path builtin_modname firmware
+
+	builtin_modinfo_path="/lib/modules/${version?}/modules.builtin.modinfo"
+	if [ ! -e "$builtin_modinfo_path" ]; then
+		if linux-version compare "${version}" ge 5.2; then
+			echo "W: Can't find modules.builtin.modinfo (for locating built-in drivers' firmware, supported in Linux >=5.2)" >&2
+		fi
+		return
+	fi
+
+	tr '\0' '\n' < "$builtin_modinfo_path" | grep -E '^[^=]*\.firmware=' | sed -n 's/\.firmware=/\t/p' | while read -r builtin_modname firmware; do
+		if ! add_firmware "$firmware"; then
+			echo "W: Possible missing firmware /lib/firmware/${firmware} for built-in driver ${builtin_modname}" >&2
+		fi
 	done
 }
 
